### ISSUE TITLE
Why give google a free pass?

### ISSUE THREAD

**Issue by ryanbr** [Sonic5435325/acceptableads#1]
See no point giving google special access. Its just another advertiser.

https://guardyourdomain.com/blog/google-ads-phishing/

**Comment by Sonic5435325** [comment]
Thanks. I have removed cosmetic filters specific to google.com and others themselves.
This filter list of mine is still new, so I appreciate the input.
https://github.com/Sonic5435325/acceptableads/commit/61c0b9562a90da7209c2fa434f6a8c6b15c20907
https://github.com/Sonic5435325/acceptableads/commit/5f64525c07d87e38f28115389c730e3ee4e91635

**Comment by Sonic5435325** [comment]
Decided to also remove YouTube exceptions
Edit: Also decided to remove DuckDuckGo exceptions in case if it causes the same problem
